meta_title       : "monea - because it's cool to exchange with monea"
meta_description : "By-pass foreign exchange desk"
meta_image       : "monea-avatar-01.png"
twitter_account  : "@nomdevotrecompte"
